version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  backend:
    image: php:7.4-fpm
    volumes:
      - ./back:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
