version: '3'
services:
  frontend:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./front:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    volumes:
      - ./back:/var/www/html
      - ./php.conf/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php.conf/www.conf:/usr/local/etc/php-fpm.d/www.conf
    depends_on:
      - postgres
    environment:
      - DB_NAME=${POSTGRES_DB}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
    restart: always

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
